spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot3_java_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 233233
  redis:
    port: 6379
    host: localhost
#  jackson:
#    property-naming-strategy: SNAKE_CASE

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: hanami@233323332333233323332333233323332333
  expiration: 86400000